### ISSUE TITLE
Fatal error: java.lang.NoClassDefFoundError: reactor/core/publisher/Mono when building a graalVM native image which has nothing to do with reactive

### ISSUE THREAD

**Issue by ryleighmikami** [micrometer-metrics/tracing#1096]
Hello team,

I am currently working with a spring boot 3.5.0 application, with java 24.
Both are latest as of this writing.

The "special" thing is that I am using a preview feature, in my case, structured concurrency.

```
package org.example;

import io.micrometer.context.ContextRegistry;
import io.micrometer.context.ContextSnapshot;
import io.micrometer.context.ContextSnapshotFactory;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.concurrent.StructuredTaskScope;

@RestController
class QuestionController {

    @GetMapping(value = "/test")
    String events() {
        try (var scope = new StructuredTaskScope.ShutdownOnFailure()) {
            final ContextSnapshot snapshot = ContextSnapshotFactory.builder().contextRegistry(ContextRegistry.getInstance()).build().captureAll();
            final StructuredTaskScope.Subtask<String> aaa = scope.fork(snapshot.wrap(() -> "aaa"));
            final StructuredTaskScope.Subtask<String> bbb = scope.fork(snapshot.wrap(() -> "bbb"));
            scope.join();
            final String stringresult = aaa.get() + bbb.get();
            return stringresult;
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

}

``` 

you can see in the above, there are reference to StructuredTaskScope, but most of all ContextRegistry, ContextSnapshot, ContextSnapshotFactory.

For this to work, this is my pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.0</version>
        <relativePath/>
    </parent>

    <groupId>org.example</groupId>
    <artifactId>preview</artifactId>
    <version>1.1</version>

    <properties>
        <java.version>24</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <env>
                            <BP_JVM_VERSION>24</BP_JVM_VERSION>
                            <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>--enable-preview</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                        </env>
                    </image>
                    <compilerArguments>--enable-preview</compilerArguments>
                    <jvmArguments>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ --enable-preview</jvmArguments>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>24</source>
                    <target>24</target>
                    <compilerArgs>--enable-preview</compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

You can see, everything is pretty latest, and the build do mention building a native image, with preview feature.

Here is the main file just to glue everything (the example is now minimal reproducible)

```
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class QuestionApplication {

    public static void main(final String[] args) {
        SpringApplication.run(QuestionApplication.class);
    }

}

```

When building the application, 100% reproducible, there is this issue:

```
[INFO]     [creator]     [2/8] Performing analysis...  []                                (24.2s @ 1.20GB)
[INFO]     [creator]        13,048 reachable types   (79.2% of   16,482 total)
[INFO]     [creator]        16,564 reachable fields  (50.4% of   32,882 total)
[INFO]     [creator]        51,804 reachable methods (45.5% of  113,968 total)
[INFO]     [creator]         5,429 types,   251 fields, and 1,398 methods registered for reflection
[INFO]     [creator]     
[INFO]     [creator]     Fatal error: java.lang.NoClassDefFoundError: reactor/core/publisher/Mono
[INFO]     [creator]     	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[INFO]     [creator]     	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3035)
[INFO]     [creator]     	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2422)
[INFO]     [creator]     	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.lambda$registerMethodLookup$0(ReflectionDataBuilder.java:500)
[INFO]     [creator]     	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.lambda$runConditionalInAnalysisTask$1(ReflectionDataBuilder.java:184)
[INFO]     [creator]     	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:166)
[INFO]     [creator]     	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:152)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1735)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1650)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1394)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1970)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[INFO]     [creator]     Caused by: java.lang.ClassNotFoundException: reactor.core.publisher.Mono
[INFO]     [creator]     	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
[INFO]     [creator]     	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
[INFO]     [creator]     	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoader.loadClass(NativeImageClassLoader.java:682)
[INFO]     [creator]     	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
[INFO]     [creator]     	... 14 more
```

The thing is, my application has nothing reactive. It is a plain old spring boot "mvc", non reactive application.

May I ask why this reliance on reactor/core/publisher/Mono?

Hopefully, I will not need to import anything from the reactor world.

Just to provide justification, and that I am not trying to waste time, if I remove:

```
  <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
        </dependency>
```

And remove the `            final ContextSnapshot snapshot = ContextSnapshotFactory.builder().contextRegistry(ContextRegistry.getInstance()).build().captureAll();
`

and all reference to this, keeping everything else, the native image will work, build is ok, run is ok.

With that said, no more observability.

Could you please help on this issue?

Thank you for your time

**Comment by ryleighmikami** [comment]
Here is the minimal reproducible 

[preview.zip](https://github.com/user-attachments/files/20771393/preview.zip)

Just run `mvn -Pnative spring-boot:build-image`

Can you reproduce the issue?

**Comment by ryleighmikami** [comment]
From there, can you just replace the pom to:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.0</version>
        <relativePath/>
    </parent>

    <groupId>org.example</groupId>
    <artifactId>preview</artifactId>
    <version>1.1</version>

    <properties>
        <java.version>24</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp</artifactId>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>io.micrometer</groupId>-->
<!--            <artifactId>micrometer-tracing-bridge-otel</artifactId>-->
<!--        </dependency>-->

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <env>
                            <BP_JVM_VERSION>24</BP_JVM_VERSION>
                            <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>--enable-preview</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                        </env>
                    </image>
                    <compilerArguments>--enable-preview</compilerArguments>
                    <jvmArguments>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ --enable-preview</jvmArguments>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>24</source>
                    <target>24</target>
                    <compilerArgs>--enable-preview</compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

And the controller to

```
package org.example;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.concurrent.StructuredTaskScope;

@RestController
class QuestionController {

    @GetMapping(value = "/test")
    String events() {
        try (var scope = new StructuredTaskScope.ShutdownOnFailure()) {
//            final ContextSnapshot snapshot = ContextSnapshotFactory.builder().contextRegistry(ContextRegistry.getInstance()).build().captureAll();
            final StructuredTaskScope.Subtask<String> aaa = scope.fork(() -> "aaa");
            final StructuredTaskScope.Subtask<String> bbb = scope.fork(() -> "bbb");
            scope.join();
            final String stringresult = aaa.get() + bbb.get();
            return stringresult;
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

}

``` 

Can you see the issue disappeared?

**Comment by ryleighmikami** [comment]
2) Also, what happens if you remove Micrometer Tracing but add context-propagation?

If you mean using this pom instead:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.0</version>
        <relativePath/>
    </parent>

    <groupId>org.example</groupId>
    <artifactId>preview</artifactId>
    <version>1.1</version>

    <properties>
        <java.version>24</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp</artifactId>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>io.micrometer</groupId>-->
<!--            <artifactId>micrometer-tracing-bridge-otel</artifactId>-->
<!--        </dependency>-->

        <!-- https://mvnrepository.com/artifact/io.micrometer/context-propagation -->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>context-propagation</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <env>
                            <BP_JVM_VERSION>24</BP_JVM_VERSION>
                            <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>--enable-preview</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                        </env>
                    </image>
                    <compilerArguments>--enable-preview</compilerArguments>
                    <jvmArguments>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/ --enable-preview</jvmArguments>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>24</source>
                    <target>24</target>
                    <compilerArgs>--enable-preview</compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

Please note micrometer-tracing-bridge-otel is now commented out, while context-propagation is there:

The code compiles as well.

But the error is still present

**Comment by ryleighmikami** [comment]
3/ Could you please attach the bottom of the stacktrace? Like where that call is coming from?

Apologies, since the stack trace is from the `mvn -Pnative spring-boot:build-image` goal, even with debug or verbose, I am not able to get the 14 more...

Do you mind just unzip the minimal reproducible? Do you get the same issue as I do?

**Comment by shakuzen** [comment]
Understood. But we're not doing anything, as far as I'm aware, that should cause the native image build to try to load Reactor classes when Reactor isn't on the classpath. It may be a bug in GraalVM - see https://github.com/oracle/graal/issues/11279.

**Comment by shakuzen** [comment]
Looking more deeply, `ReactiveSecurityContextHolderThreadLocalAccessor` is new in Spring Security 6.5, and the ServiceLoader in context-propagation will try to load that when the class ContextRegistry is loaded. Perhaps that is where native image is reaching Mono. It really should be easier to determine that from the output of native image, though.

**Comment by shakuzen** [comment]
@ryleighmikami could you try with Spring Boot 3.4 (which manages Spring Security to 6.4) and see if the issue goes away?

**Comment by shakuzen** [comment]
Thanks for trying that for us. Does it work with Spring Boot 3.5 and GraalVM 21? Hold off on opening an issue just yet. We want to make sure we understand the full picture first.

**Comment by jonatan-ivanov** [comment]
>Are you saying inal ContextSnapshot snapshot = ContextSnapshotFactory.builder().contextRegistry(ContextRegistry.getInstance()).build().captureAll(); + scope.fork(snapshot.wrap(() ->  is incorrect?

No, I said, you have alternatives. It turned out it does not matter, those alternatives won't help either (see below).

I was able to repro and remove things from your sample keeping the behavior (build fail), you can find it here: https://github.com/jonatan-ivanov/micrometer-tracing-gh-1096.

Please check the readme, summary:
- `spring-security-core` and `context-propagation` are the magic combination, if you remove either of them, the build is ok. This points towards [Tommy's findings about `ReactiveSecurityContextHolderThreadLocalAccessor`](https://github.com/micrometer-metrics/tracing/issues/1096#issuecomment-2983229260)
- It fails on Graal 24, it's ok on Graal 21 and Graal 17. This points towards [Tommy's comment about the GraalVM issue](https://github.com/micrometer-metrics/tracinag/issues/1096#issuecomment-2983027535)

It seems an immediate workaround would be not using structured concurrency and downgrading GraalVM. Could you please check if downgrading GraalVM works in your real-world app?

**Comment by shakuzen** [comment]
> 1. Structured concurrency. Without it, our responses are too slow, we will be out of business

There are many widely used ways to run Java code concurrently, since long before the introduction of Structured Concurrency. Also, Structured Concurrency is still a preview feature.

> Is there a way, using Structured concurrency, GraalVM24, Springboot 3.5, to still have trace in the structured task scope?

We don't know what we could change to work around the issue because it's not 100% clear what the root cause is. Ideally the GraalVM team could identify the root cause and we can work from there. I've left a comment on the GraalVM issue to offer whatever help we can provide to the GraalVM team in identify the root cause.

**Comment by ryleighmikami** [comment]
Many thanks @shakuzen

**Comment by shakuzen** [comment]
I think we can close this issue for now. As far as we can tell, it is an issue in GraalVM 24 that's causing this, and there's no apparent change we can make to work around it at this time. If that changes, we can re-open this.
